-- MySQL Script generated by MySQL Workbench
-- Thu Nov 10 02:46:57 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cl` VARCHAR(45) NOT NULL,
  `vehiculo_cl` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC) VISIBLE)
ENGINE = InnoDB;

ALTER TABLE Cliente DROP COLUMN vehiculo_cl;

select * from Cliente;

-- -----------------------------------------------------
-- Table `mydb`.`Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vehiculo` (
  `idVehiculo` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(10) NULL,
  `modelo` VARCHAR(10) NULL,
  `placa` VARCHAR(10) NULL,
  `serial` VARCHAR(45) NULL,
  `propietario` INT NULL,
  PRIMARY KEY (`idVehiculo`),
  UNIQUE INDEX `idVehiculo_UNIQUE` (`idVehiculo` ASC) VISIBLE,
  UNIQUE INDEX `Marca_UNIQUE` (`marca` ASC) VISIBLE,
  UNIQUE INDEX `Modelo_UNIQUE` (`modelo` ASC) VISIBLE,
  UNIQUE INDEX `serial_UNIQUE` (`serial` ASC) VISIBLE,
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC) VISIBLE,
  UNIQUE INDEX `propietario_UNIQUE` (`propietario` ASC) VISIBLE,
  CONSTRAINT `idCliente`
    FOREIGN KEY (`propietario`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

DROP INDEX `Marca_UNIQUE` ON mydb.Vehiculo;
DROP INDEX `Modelo_UNIQUE` ON mydb.Vehiculo;

CREATE INDEX `Marca` ON Vehiculo (`marca` ASC) VISIBLE;
CREATE INDEX `Model` ON Vehiculo (`modelo` ASC) VISIBLE;

ALTER TABLE Vehiculo DROP FOREIGN KEY `idCliente`;

DROP INDEX `propietario_UNIQUE` ON mydb.Vehiculo;
CREATE INDEX `Propietario` ON Vehiculo (`propietario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mecanico` (
  `idMecanico` INT NOT NULL AUTO_INCREMENT,
  `nome_mec` VARCHAR(45) NULL,
  `espec_mec` VARCHAR(10) NULL,
  `team_mec` INT NULL,
  PRIMARY KEY (`idMecanico`),
  UNIQUE INDEX `idMecanico_UNIQUE` (`idMecanico` ASC) VISIBLE,
  UNIQUE INDEX `nome_mec_UNIQUE` (`nome_mec` ASC) VISIBLE,
  UNIQUE INDEX `espec_mec_UNIQUE` (`espec_mec` ASC) VISIBLE,
  UNIQUE INDEX `team_mec_UNIQUE` (`team_mec` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teams` (
  `idTeams` INT NOT NULL AUTO_INCREMENT,
  `nome_team` VARCHAR(45) NOT NULL,
  `membro_team` INT NULL,
  PRIMARY KEY (`idTeams`),
  UNIQUE INDEX `idTeams_UNIQUE` (`idTeams` ASC) VISIBLE,
  UNIQUE INDEX `nome_team_UNIQUE` (`nome_team` ASC) VISIBLE,
  INDEX `idMecanico_idx` (`membro_team` ASC) VISIBLE,
  CONSTRAINT `idMecanico`
    FOREIGN KEY (`membro_team`)
    REFERENCES `mydb`.`Mecanico` (`idMecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Serviço` (
  `idServiço` INT NOT NULL AUTO_INCREMENT,
  `nome_serviço` VARCHAR(20) NULL,
  `valor_serviço` FLOAT NULL,
  `team_serviço` INT NULL,
  PRIMARY KEY (`idServiço`),
  UNIQUE INDEX `idServiço_UNIQUE` (`idServiço` ASC) VISIBLE,
  UNIQUE INDEX `nome_serviço_UNIQUE` (`nome_serviço` ASC) VISIBLE,
  UNIQUE INDEX `valor_serviço_UNIQUE` (`valor_serviço` ASC) VISIBLE,
  UNIQUE INDEX `team_serviço_UNIQUE` (`team_serviço` ASC) VISIBLE,
  CONSTRAINT `idTeam`
    FOREIGN KEY (`team_serviço`)
    REFERENCES `mydb`.`Teams` (`idTeams`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peças`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peças` (
  `idPeças` INT NOT NULL AUTO_INCREMENT,
  `nome_peça` VARCHAR(20) NULL,
  `valor_peça` FLOAT NULL,
  `team_serv` INT NULL,
  PRIMARY KEY (`idPeças`),
  UNIQUE INDEX `idPeças_UNIQUE` (`idPeças` ASC) VISIBLE,
  UNIQUE INDEX `nome_peça_UNIQUE` (`nome_peça` ASC) VISIBLE,
  INDEX `idTeam_idx` (`team_serv` ASC) VISIBLE,
  -- INDEX `fk_valor_peça` (`valor_peça` ASC) VISIBLE,
  CONSTRAINT `idTeams`
    FOREIGN KEY (`team_serv`)
    REFERENCES `mydb`.`Teams` (`idTeams`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_valor_peça` ON Peças (`valor_peça`);

-- -----------------------------------------------------
-- Table `mydb`.`Orden de Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orden de Serviço` (
  `idtOS` INT NOT NULL AUTO_INCREMENT,
  `cliente_OS` INT NULL,
  `vehiculo_OS` INT NULL,
  `team_OS` INT NULL,
  `Valor_OS` FLOAT NULL,
  `data_in_OS` DATE NULL,
  `data_out_OS` DATE NULL,
  `status_OS` ENUM('Ordered', 'In Work', 'Finished') NULL,
  `servico_OS` INT NULL,
  `peça_OS` INT NULL,
  PRIMARY KEY (`idtOS`),
  UNIQUE INDEX `idtOS_UNIQUE` (`idtOS` ASC) VISIBLE,
  UNIQUE INDEX `cliente_OS_UNIQUE` (`cliente_OS` ASC) VISIBLE,
  UNIQUE INDEX `vehiculo_OS_UNIQUE` (`vehiculo_OS` ASC) VISIBLE,
  UNIQUE INDEX `data_in_OS_UNIQUE` (`data_in_OS` ASC) VISIBLE,
  UNIQUE INDEX `data_out_OSl_UNIQUE` (`data_out_OS` ASC) VISIBLE,
  UNIQUE INDEX `status_OS_UNIQUE` (`status_OS` ASC) VISIBLE,
  INDEX `idServiço_idx` (`servico_OS` ASC) VISIBLE,
  INDEX `idPeças_idx` (`peça_OS` ASC) VISIBLE,
  CONSTRAINT `idClientes`
    FOREIGN KEY (`cliente_OS`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idVehiculo`
    FOREIGN KEY (`vehiculo_OS`)
    REFERENCES `mydb`.`Vehiculo` (`idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idServiço`
    FOREIGN KEY (`servico_OS`)
    REFERENCES `mydb`.`Serviço` (`idServiço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPeças`
    FOREIGN KEY (`peça_OS`)
    REFERENCES `mydb`.`Peças` (`idPeças`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Orçamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orçamento` (
  `idOrçamento` INT NOT NULL,
  `serv_or`     INT NOT NULL,
  `valor_serv_or` FLOAT NULL,
  `peça_or`     INT NOT NULL,
  `valor_peça_or` FLOAT NULL,
  `team_serv_or` INT NOT NULL,
  PRIMARY KEY (`idOrçamento`),
  INDEX `idPeças_idx` (`peça_or` ASC) VISIBLE,
  INDEX `idTeam_idx` (`team_serv_or` ASC) VISIBLE,
  INDEX `idServiço_idx` (`serv_or` ASC) VISIBLE,
  INDEX `valor_peça` (`valor_peça_or` ASC) VISIBLE,
  INDEX `valor_serviço` (`valor_serv_or` ASC) VISIBLE,
  CONSTRAINT `fk_team`
    FOREIGN KEY (`team_serv_or`)
    REFERENCES `mydb`.`Teams` (`idTeams`),
  CONSTRAINT `fk_type_peça`
    FOREIGN KEY (`peça_or`)
    REFERENCES `mydb`.`Peças` (`idPeças`),
  CONSTRAINT `fk_type_serv`
    FOREIGN KEY (`serv_or`)
    REFERENCES `mydb`.`Serviços` (`idServiços`),
  CONSTRAINT `fk_valor_peça`
    FOREIGN KEY (`valor_peça_or`)
    REFERENCES `mydb`.`Peças` (`valor_peça`),
  CONSTRAINT `fk_valor_serv`
    FOREIGN KEY (`valor_serv_or`)
    REFERENCES `mydb`.`Serviço` (`valor_serviço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

ALTER TABLE Cliente
ADD endereço_cl VARCHAR(20) NOT NULL;

ALTER TABLE Cliente
ADD cpf_cl VARCHAR(11) NOT NULL,
ADD telefone_cl VARCHAR(11) NOT NULL;

select * from Mecanico;

INSERT INTO Serviço VALUES
	(1,	'Hidraulico', 300.00, 1),
	(default, 'Mecanico', 600.00, 2),
	(default, 'Eletrico', 700.00, 3),
	(default,'Lataria', 500.00, 4),
	(default, 'Ar Condicionado', 200.00, 5),
	(default, 'Limpeça', 50.00,	6);
  
  select * from Mecanico;
  
  DROP INDEX `team_mec_UNIQUE` ON mydb.Mecanico;
  
  CREATE INDEX `team_mec` ON Mecanico(`team_mec` ASC) VISIBLE;
  
  INSERT INTO Mecanico VALUES
		(1,	"João Gabriel", "Hidraulico", 1);

  DROP INDEX `espec_mec_UNIQUE` ON mydb.Mecanico;
  
  CREATE INDEX `espec_mec` ON Mecanico(`espec_mec` ASC) VISIBLE;
   
INSERT INTO Mecanico VALUES
		(default, "Roberto Antonio", "Mecanico", 1),
		(default, "Marcel Granier", "Eletrico", 2),
		(default, "Gabriel Garcial", "Lataria", 3),
		(default, "Marcelo Antonio", "Ar Cond", 2),
		(default, "Samuel Jose", "Limpeça", 4),
		(default, "Josue Alberto", "Hidraulico", 1),
		(default, "Alberto", "Mecanico", 1),
		(default, "Damian", "Eletrico", 2),
		(default, "Carlos Enrique", "Ar Cond", 2),
        (default, "Ricardo", "Limpeça", 4), 
		(default, "Jose Ricardo", "Hidraulico", 1),
		(default, "Jose Roberto", "Lataria", 3);
        
INSERT INTO Peças VALUES
	(1, 'Motor 1', 300.00, 1),
	(default, 'Motor 2', 600.00, 1),
	(default, 'Embriagem 1', 700.00, 2),
	(default, 'Embriagem 2', 500.00, 2),
	(default, 'Retrovisor', 200.00, 4),
	(default, 'Vidro porta', 50.00,	4),
	(default, 'Vidro frente', 300.00, 4),
	(default, 'Vidro traseiro',	600.00,	4),
	(default, 'Pneu', 700.00, 1),
	(default, 'Transitor', 500.00, 3);

select * from Vehiculo;

INSERT INTO Vehiculo VALUES
	(1,'Fiat', 'Argo', 'GHY8U76', 'HD73JASYR9',	1),
	(default, 'Ford',	'Focus', 'GHT7F65', 'DGATW53UDO', 2),
	(default, 'VW',	'Fox', 'FRT5F34', 'HS73TETE64', 2),
	(default, 'Renault', 'Kwid', 'GHL0J90', '0KUYTRDSW3', 3),
	(default, 'Jeep', 'Renegate', 'BFG8J65', 'BVC654RDE3', 4),
	(default, 'Chevrolet', 'Onix', 'BFT5J98', 'LO8UHY65TR',	5),
	(default, 'Renault', 'Kwid', 'FDR5H78', 'NMJHUY65RE', 5);

select * from Cliente;

INSERT INTO Cliente VALUES
	(1,	"Laura",	"Mooca",	'83402348533',	'11862625353'),
	(2,	"Adrian",	"República",	'83212398456',	'11834226543'),
	(3,	"Roberto",	"Consolação",	'43587509723',	'11878734543'),
	(4,	"Maria",	"Vila Buarque",	'49550675922',	'11809890032'),
	(5,	"Carmen",	"Santa Cecilia",	'40665230044',	'11890893333');
    
Select * from Cliente, Vehiculo where propietario=idCliente and idCliente = 2;






